//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeWee_DBEntities : DbContext
    {
        public DeWee_DBEntities()
            : base("name=DeWee_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Tbl_Block_Master> Tbl_Block_Master { get; set; }
        public virtual DbSet<Tbl_BusinessInvestmentM> Tbl_BusinessInvestmentM { get; set; }
        public virtual DbSet<Tbl_BusinessOwnedM> Tbl_BusinessOwnedM { get; set; }
        public virtual DbSet<Tbl_BusinessTypeM> Tbl_BusinessTypeM { get; set; }
        public virtual DbSet<Tbl_CasteM> Tbl_CasteM { get; set; }
        public virtual DbSet<Tbl_CLF_Master> Tbl_CLF_Master { get; set; }
        public virtual DbSet<Tbl_District_Master> Tbl_District_Master { get; set; }
        public virtual DbSet<Tbl_ElectricityConsumptionM> Tbl_ElectricityConsumptionM { get; set; }
        public virtual DbSet<Tbl_ElectricityUsedM> Tbl_ElectricityUsedM { get; set; }
        public virtual DbSet<Tbl_MachineryPowerM> Tbl_MachineryPowerM { get; set; }
        public virtual DbSet<Tbl_MoneySavedSEM> Tbl_MoneySavedSEM { get; set; }
        public virtual DbSet<Tbl_MonthlyExpenseEBM> Tbl_MonthlyExpenseEBM { get; set; }
        public virtual DbSet<Tbl_Panchayat_Master> Tbl_Panchayat_Master { get; set; }
        public virtual DbSet<Tbl_PowerConnectionM> Tbl_PowerConnectionM { get; set; }
        public virtual DbSet<Tbl_SolarkilowattM> Tbl_SolarkilowattM { get; set; }
        public virtual DbSet<Tbl_SourceEnergyM> Tbl_SourceEnergyM { get; set; }
        public virtual DbSet<Tbl_State_Master> Tbl_State_Master { get; set; }
        public virtual DbSet<Tbl_SubisdyM> Tbl_SubisdyM { get; set; }
        public virtual DbSet<Tbl_TypeYesNoM> Tbl_TypeYesNoM { get; set; }
        public virtual DbSet<Tbl_Village_Master> Tbl_Village_Master { get; set; }
        public virtual DbSet<Tbl_VO_Master> Tbl_VO_Master { get; set; }
        public virtual DbSet<Tbl_Educational_QualificationM> Tbl_Educational_QualificationM { get; set; }
        public virtual DbSet<Tbl_Enterprise_EstablishedM> Tbl_Enterprise_EstablishedM { get; set; }
        public virtual DbSet<Tbl_EnterpriseM> Tbl_EnterpriseM { get; set; }
        public virtual DbSet<Tbl_EnterpriseMachineM> Tbl_EnterpriseMachineM { get; set; }
        public virtual DbSet<Tbl_IndtSolarization> Tbl_IndtSolarization { get; set; }
        public virtual DbSet<Tbl_LoanDescribeSourceM> Tbl_LoanDescribeSourceM { get; set; }
    }
}
