//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CreditProfile
    {
        public int ID { get; set; }
        public string BeneficiaryId { get; set; }
        public Nullable<int> SolarSolution { get; set; }
        public Nullable<int> Getloan { get; set; }
        public string Getloan_Other { get; set; }
        public string ActiveLoan { get; set; }
        public string SHGMeetingsPresent { get; set; }
        public string LoanSHGPreviously { get; set; }
        public string SHGTaken { get; set; }
        public string SHGFold { get; set; }
        public string IdentificationId { get; set; }
        public string LoanAmount { get; set; }
        public Nullable<System.DateTime> LoanProcessDate { get; set; }
        public Nullable<System.DateTime> LoanDisbursementDate { get; set; }
        public Nullable<int> ApplicationRejected { get; set; }
        public string ApplicationRejected_Other { get; set; }
        public string EMIDuration { get; set; }
        public string EMIAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Version { get; set; }
        public string uuid { get; set; }
        public Nullable<System.DateTime> SynDate { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CeeatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
    }
}
