//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SolarShop
    {
        public int SolarShopId_pk { get; set; }
        public string NameofEnterprise { get; set; }
        public string NameofOwner { get; set; }
        public Nullable<int> TypeofEnterprise { get; set; }
        public string Other_TypeofEnterprise { get; set; }
        public string PrimaryMobileNo { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string SiteAddress { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
        public string Iflinked { get; set; }
        public string uuid { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> SynDate { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string SolarShopEnterprisePicPath { get; set; }
    }
}
