//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Panchayat_Master
    {
        public int PanchayatId_pk { get; set; }
        public Nullable<int> DistrictId_fk { get; set; }
        public Nullable<int> BlockId_fk { get; set; }
        public Nullable<int> CLFId_fk { get; set; }
        public string PanchayatName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrderBy { get; set; }
    }
}
