//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InstallationCommission
    {
        public int ID { get; set; }
        public string BeneficiaryId { get; set; }
        public string NameofVendor { get; set; }
        public Nullable<System.DateTime> DateofInstallation { get; set; }
        public Nullable<System.DateTime> DateofCommissioning { get; set; }
        public Nullable<System.DateTime> DateofTraining { get; set; }
        public Nullable<int> GHGEmissionYearlyKgs { get; set; }
        public Nullable<int> Numberofwomenemployed { get; set; }
        public Nullable<int> InverterWarranty { get; set; }
        public Nullable<int> AnnualMaintenanceDue { get; set; }
        public string ServiceContact { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string InverterName { get; set; }
        public string BatteryName { get; set; }
        public string BatteryWarranty { get; set; }
        public string SolarName { get; set; }
        public string SolarWarranty { get; set; }
        public string VfbMotorName { get; set; }
        public string VfbWarranty { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Version { get; set; }
        public string uuid { get; set; }
        public Nullable<System.DateTime> SynDate { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
