//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IndtSolarization
    {
        public System.Guid Indt_Id { get; set; }
        public Nullable<int> State_Id { get; set; }
        public Nullable<int> District_Id { get; set; }
        public Nullable<int> Block_Id { get; set; }
        public Nullable<int> Panchayat_Id { get; set; }
        public Nullable<int> Village_Id { get; set; }
        public Nullable<int> CLF_Id { get; set; }
        public Nullable<int> VO_Id { get; set; }
        public string TempRegNo { get; set; }
        public string RegNo { get; set; }
        public string AadharNo { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> YearOfSHG { get; set; }
        public string NameofSHGmember { get; set; }
        public string NameofEnterpriseOwner { get; set; }
        public Nullable<int> Age { get; set; }
        public string DOB { get; set; }
        public Nullable<int> EducationQlf_Id { get; set; }
        public Nullable<int> Caste_Id { get; set; }
        public Nullable<int> TypeofEnterpriseBusin_Id { get; set; }
        public Nullable<int> BusinessOwnedType_Id { get; set; }
        public Nullable<int> EstablishedEnterpriseType_Id { get; set; }
        public Nullable<int> TypeOfInvestBusin_Id { get; set; }
        public Nullable<int> TookSourceOfLoan_Id { get; set; }
        public Nullable<decimal> TookLoanAmt { get; set; }
        public Nullable<decimal> StartBusinessInvestAmt { get; set; }
        public Nullable<decimal> StartYourBusinessTakeAmt { get; set; }
        public Nullable<decimal> MonthlyProfitBusiness { get; set; }
        public Nullable<int> WorkInEnterprises_FamilyMembers { get; set; }
        public Nullable<int> WorkInEnterprises_SHGMembers { get; set; }
        public Nullable<int> WorkInEnterprises_AssitantStaffs { get; set; }
        public Nullable<int> TypeOfMachineEnterprise_Id { get; set; }
        public Nullable<int> MotorBasedOnMachinesInActualUsed { get; set; }
        public Nullable<int> MachineryPowerkilowatt_Id { get; set; }
        public Nullable<int> ElectricityConnection_Id { get; set; }
        public Nullable<int> ConnectionPhaseofPower_Id { get; set; }
        public Nullable<int> MonthlyElectricityConsumption_Id { get; set; }
        public Nullable<int> MachineSourceofEnergy_Id { get; set; }
        public Nullable<int> Solar_InKilowatt_Id { get; set; }
        public Nullable<int> Solar_EnergyPanelYesNo_Id { get; set; }
        public Nullable<decimal> Solar_ExpenditureIncurredAmt { get; set; }
        public Nullable<int> Subsidy_Id { get; set; }
        public Nullable<int> LoanForSolarPanels_Id { get; set; }
        public Nullable<int> AvgAmtSavedFromSolarE_Id { get; set; }
        public Nullable<int> ElectricityUsed_Id { get; set; }
        public Nullable<int> MonthlyExpenseInElectricity_Id { get; set; }
        public Nullable<int> GeneratorElectricityUsed_Id { get; set; }
        public Nullable<int> ExpenseFuelSource_Id { get; set; }
        public Nullable<int> RepairCost_Id { get; set; }
        public Nullable<int> HeardAboutSE_Id { get; set; }
        public string IfYeswhere { get; set; }
        public Nullable<int> InformationknowledgeAboutgovtsubsidyOfSE_Id { get; set; }
        public Nullable<int> IfYesAmtGovPaid { get; set; }
        public Nullable<int> LoanProcedureInSE_Id { get; set; }
        public Nullable<int> AdoptSolarization_Id { get; set; }
        public Nullable<int> CapitalArrangedForSE_Id { get; set; }
        public Nullable<int> IfYesCapitalArrangedForSE_Id { get; set; }
        public Nullable<int> OtherIndustriesEnterprises_Id { get; set; }
        public string IfYesFillTheForm { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        public Nullable<int> OrderBy { get; set; }
    }
}
