//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Beneficiary
    {
        public System.Guid BeneficiaryId_pk { get; set; }
        public string Temp_RegCode { get; set; }
        public string Selection_RegCode { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> GPId { get; set; }
        public string Village { get; set; }
        public string CLF { get; set; }
        public string VO { get; set; }
        public string NameofSHG { get; set; }
        public Nullable<int> YearOfSHG { get; set; }
        public string NameofEnterprise { get; set; }
        public Nullable<int> TypeofEnterpriseBusinId { get; set; }
        public string NameofSHGMember { get; set; }
        public string NameofEnterpriseOwner { get; set; }
        public string EnterpriseOwner_Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> TypeofRelative { get; set; }
        public string NameofGuardian { get; set; }
        public string Guardian_Gender { get; set; }
        public string PrimaryMobileNo { get; set; }
        public string AlternateMobileNo { get; set; }
        public Nullable<bool> IsSamePrimayMobileNo { get; set; }
        public string WhatsAppMobileNo { get; set; }
        public Nullable<int> SiteAddress1stId { get; set; }
        public string SiteAddress1st { get; set; }
        public Nullable<int> SiteAddress2ndId { get; set; }
        public string SiteAddress2nd { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<int> CategoryBusinessInstallationId { get; set; }
        public Nullable<int> SpaceAvailableId { get; set; }
        public string SpaceAvailable_Area { get; set; }
        public Nullable<int> NatureofSpaceId { get; set; }
        public string NatureofSpace_other { get; set; }
        public string YNGridconnection { get; set; }
        public string YNDieselGenerator { get; set; }
        public string YNMotorAppliances { get; set; }
        public Nullable<int> OtherSourceEnergyMachineId { get; set; }
        public string YNGovtSchemessubsidy { get; set; }
        public Nullable<int> SolarInstallationId { get; set; }
        public string YNFinancialSupport { get; set; }
        public string EnterprisePhotoPath { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
        public string Accuracy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string EnterpriseBusinId_other { get; set; }
    }
}
