//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EnergyRequirement
    {
        public int ID { get; set; }
        public string BeneficiaryId { get; set; }
        public string LoadEnterprisekW { get; set; }
        public Nullable<int> TechnicalAssessment { get; set; }
        public string TechnicalAssessment_Other { get; set; }
        public Nullable<int> CapacityInstallation { get; set; }
        public Nullable<int> SolarPVInstalledkW { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Version { get; set; }
        public string uuid { get; set; }
        public Nullable<System.DateTime> SynDate { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CeeatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
