//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IndtSolarization
    {
        public System.Guid Indt_Id { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> PanchayatId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public Nullable<int> CLFId { get; set; }
        public Nullable<int> VOId { get; set; }
        public string NameofSHG { get; set; }
        public Nullable<int> YearOfSHG { get; set; }
        public string TempRegNo { get; set; }
        public string RegNo { get; set; }
        public string AadharNo { get; set; }
        public string PhoneNumber { get; set; }
        public string NameofSHGMember { get; set; }
        public string NameofEnterpriseOwner { get; set; }
        public Nullable<int> Age { get; set; }
        public string DOB { get; set; }
        public Nullable<int> EducationQlf_Id { get; set; }
        public Nullable<int> Caste_Id { get; set; }
        public Nullable<int> TypeofEnterpriseBusin_Id { get; set; }
        public string TypeofEnterpriseBusin_Other { get; set; }
        public Nullable<int> BusinessOwnedType_Id { get; set; }
        public Nullable<int> EstablishedEnterpriseType_Id { get; set; }
        public Nullable<int> TypeOfInvestBusin_Id { get; set; }
        public Nullable<int> TookSourceOfLoan_Id { get; set; }
        public Nullable<decimal> TookLoanAmt { get; set; }
        public Nullable<decimal> StartBusinessInvestAmt { get; set; }
        public Nullable<decimal> StartYourBusinessTakeAmt { get; set; }
        public Nullable<decimal> MonthlyProfitBusiness { get; set; }
        public Nullable<int> WorkInEnterprises_FamilyMembers { get; set; }
        public Nullable<int> WorkInEnterprises_SHGMembers { get; set; }
        public Nullable<int> WorkInEnterprises_AssitantStaffs { get; set; }
        public Nullable<int> TypeOfMachineEnterprise_Id { get; set; }
        public Nullable<int> MotorBasedOnMachinesInActualUsed { get; set; }
        public Nullable<int> MachineryPowerkilowatt_Id { get; set; }
        public Nullable<int> ElectricityConnection_Id { get; set; }
        public Nullable<int> ConnectionPhaseofPower_Id { get; set; }
        public Nullable<int> MonthlyElectricityConsumption_Id { get; set; }
        public Nullable<int> MachineSourceofEnergy_Id { get; set; }
        public string MachineSourceofEnergy_Others { get; set; }
        public Nullable<int> Solar_InKilowatt_Id { get; set; }
        public Nullable<int> Solar_EnergyPanelYesNo_Id { get; set; }
        public Nullable<decimal> Solar_ExpenditureIncurredAmt { get; set; }
        public Nullable<int> SubsidySolarReceive_Id { get; set; }
        public Nullable<int> LoanSolarPanelsYesNo_Id { get; set; }
        public Nullable<int> MonthAvgAmtSavedDescription_Id { get; set; }
        public Nullable<int> ElectricityUsedHours_Id { get; set; }
        public Nullable<int> MonthlyExpenseInElectricityBill_Id { get; set; }
        public Nullable<int> GeneratorElectricityUsedHours_Id { get; set; }
        public Nullable<int> MonthlyExpenseFuelSource_Id { get; set; }
        public Nullable<int> MonthlyRepairCost_Id { get; set; }
        public Nullable<int> HeardAboutSolarEYesNo_Id { get; set; }
        public string HeardAboutSolarEYes_IfYeswhere { get; set; }
        public Nullable<int> InforknowledgeGovtSubsidyOfSEYesNo_Id { get; set; }
        public Nullable<decimal> InforknowledgeIfYesAmtGovPaid { get; set; }
        public Nullable<int> LoanProcedureInSEYesNo_Id { get; set; }
        public Nullable<int> AdoptSolarizationYesNo_Id { get; set; }
        public Nullable<int> CapitalArrangedForSEYesNo_Id { get; set; }
        public Nullable<decimal> IfYesCapitalArrangedForSEAmt { get; set; }
        public Nullable<int> OtherIndustriesEnterprisesYesNo_Id { get; set; }
        public string IfYesFillForm_OtherIndustriesEnterprises { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
        public string Accuracy { get; set; }
        public string ParticipantPicPath { get; set; }
        public string SolarEnterprisePicPath { get; set; }
    }
}
