//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeWee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_THR
    {
        public int THRId_pk { get; set; }
        public Nullable<int> StateId_fk { get; set; }
        public Nullable<int> DistrictId_fk { get; set; }
        public Nullable<int> BlockId_fk { get; set; }
        public Nullable<int> GPId_fk { get; set; }
        public string TypeTHR { get; set; }
        public Nullable<int> TypeofEnterpriseId { get; set; }
        public string THR_NutriEnterprise { get; set; }
        public string TypeofRoof { get; set; }
        public string TRoofandshedareaavailable_sqfeet { get; set; }
        public string AreaAvailableSolarization_sqfeet { get; set; }
        public string PersonName { get; set; }
        public string PhoneNumber { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
        public Nullable<bool> IsSolarized { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
